/* eslint-disable */
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) { // AMD
    define([], factory);
  } else if (typeof exports === 'object') { // Node.js
    module.exports = factory();
  } else { // Browser
    var messages = factory();
    for (var key in messages) {
      root.Blockly.Msg[key] = messages[key];
    }
  }
}(this, function() {
// This file was automatically generated.  Do not modify.

'use strict';

var Blockly = Blockly || { Msg: Object.create(null) };

Blockly.Msg["ADD_COMMENT"] = "Добавить комментарий";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Нельзя удалить переменную «%1», потому что она участвует в определении функции «%2».";
Blockly.Msg["CHANGE_VALUE_TITLE"] = "Изменить значение:";
Blockly.Msg["CLEAN_UP"] = "Упорядочить блоки";
Blockly.Msg["COLLAPSED_WARNINGS_WARNING"] = "Свёрнутые блоки содержат предупреждения.";
Blockly.Msg["COLLAPSE_ALL"] = "Свернуть блоки";
Blockly.Msg["COLLAPSE_BLOCK"] = "Свернуть блок";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "цвет 1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "цвет 2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";
Blockly.Msg["COLOUR_BLEND_RATIO"] = "соотношение";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "смешать";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "Смешивает два цвета в заданном соотношении (0,0–1,0).";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://ru.wikipedia.org/wiki/Цвет";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "Выберите цвет из палитры.";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "случайный цвет";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "Выбирает случайный цвет.";
Blockly.Msg["COLOUR_RGB_BLUE"] = "синий";
Blockly.Msg["COLOUR_RGB_GREEN"] = "зелёный";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";
Blockly.Msg["COLOUR_RGB_RED"] = "красный";
Blockly.Msg["COLOUR_RGB_TITLE"] = "цвет из";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "Создаёт цвет с указанным количеством красного, зелёного и синего. Все значения должны быть в диапазоне от 0 до 100.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "выйти из цикла";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "перейти к следующей итерации цикла";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Выйти из текущего цикла.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Пропустить оставшуюся часть цикла и перейти к следующей итерации.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Предупреждение: этот блок можно использовать только внутри цикла.";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "для каждого элемента %1 в списке %2";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "Для каждого элемента списка присвойте переменной «%1» значение элемента, а затем выполните несколько операций.";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";
Blockly.Msg["CONTROLS_FOR_TITLE"] = "счёт с %1 от %2 до %3 шагом %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "Присвойте переменной «%1» значения от начального до конечного числа с заданным шагом и выполните указанные блоки.";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Добавить условие к блоку «если».";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "Добавить заключительное условие для блока «если».";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "Добавьте, удалите или переупорядочите секции, чтобы настроить этот блок «если».";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "иначе";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "иначе если";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "если";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "Если значение истинно, выполните несколько действий.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "Если значение истинно, выполните первый блок операций. Иначе выполните второй блок операций.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "Если первое значение истинно, выполните первый блок операций. Иначе, если второе значение истинно, выполните второй блок операций.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "Если первое значение истинно, выполните первый блок операций. Иначе, если второе значение истинно, выполните второй блок операций. Если ни одно значение не истинно, выполните последний блок операций.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://ru.wikipedia.org/wiki/Цикл_(программирование)";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "выполнить";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "повторить %1 раз";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "Выполнить несколько действий несколько раз.";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "повторять, пока не";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "повторять, пока";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Пока значение ложно, выполняйте несколько операций.";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Пока значение истинно, выполняйте несколько операций.";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "Удалить все %1 блоков?";
Blockly.Msg["DELETE_BLOCK"] = "Удалить блок";
Blockly.Msg["DELETE_VARIABLE"] = "Удалить переменную «%1»";
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "Удалить %1 использований переменной «%2»?";
Blockly.Msg["DELETE_X_BLOCKS"] = "Удалить %1 блоков";
Blockly.Msg["DIALOG_CANCEL"] = "Отмена";
Blockly.Msg["DIALOG_OK"] = "OK";
Blockly.Msg["DISABLE_BLOCK"] = "Отключить блок";
Blockly.Msg["DUPLICATE_BLOCK"] = "Дублировать";
Blockly.Msg["DUPLICATE_COMMENT"] = "Дублировать комментарий";
Blockly.Msg["ENABLE_BLOCK"] = "Включить блок";
Blockly.Msg["EXPAND_ALL"] = "Развернуть блоки";
Blockly.Msg["EXPAND_BLOCK"] = "Развернуть блок";
Blockly.Msg["EXTERNAL_INPUTS"] = "Внешние входы";
Blockly.Msg["HELP"] = "Справка";
Blockly.Msg["INLINE_INPUTS"] = "Встроенные входы";
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "создать пустой список";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "Возвращает список длиной 0, который не содержит записей данных.";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "список";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Добавляйте, удаляйте или меняйте порядок секций, чтобы настроить этот блок списка.";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "создать список из";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Добавить элемент в список.";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "Создаёт список из любого количества элементов.";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "первый";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "# с конца";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "получить";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "получить и удалить";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "последний";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "случайный";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "удалить";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Возвращает первый элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Возвращает элемент в указанной позиции списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Возвращает последний элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Возвращает случайный элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Удаляет и возвращает первый элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Удаляет и возвращает элемент в указанной позиции списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Удаляет и возвращает последний элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Удаляет и возвращает случайный элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Удаляет первый элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Удаляет элемент в указанной позиции списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Удаляет последний элемент списка.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Удаляет случайный элемент списка.";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "до # с конца";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "до #";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "до последнего";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "получить подсписок от начала";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "получить подсписок от # с конца";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "получить подсписок от #";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "";
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "Создаёт копию указанной части списка.";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 — это последний элемент.";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 — это первый элемент.";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "найти первое вхождение элемента";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "найти последнее вхождение элемента";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "Возвращает позицию первого или последнего вхождения элемента в список. Возвращает %1, если элемент не найден.";
Blockly.Msg["LISTS_INLIST"] = "в списке";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "%1 пуст";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "Возвращает true, если список пуст.";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";
Blockly.Msg["LISTS_LENGTH_TITLE"] = "длина %1";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "Возвращает длину списка.";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg["LISTS_REPEAT_TITLE"] = "создать список из элемента %1, повторённого %2 раз";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "Создаёт список, состоящий из заданного значения, повторённого указанное число раз.";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "изменить порядок %1 на обратный";
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "Меняет порядок элементов в копии списка на обратный.";
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "как";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "вставить в";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "присвоить";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Вставляет элемент в начало списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Вставляет элемент в указанную позицию списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Добавляет элемент в конец списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Вставляет элемент в случайную позицию списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Устанавливает первый элемент списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Устанавливает элемент в указанной позиции списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Устанавливает последний элемент списка.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Устанавливает случайный элемент списка.";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "по возрастанию";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "по убыванию";
Blockly.Msg["LISTS_SORT_TITLE"] = "сортировать %1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "Сортирует копию списка.";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "по алфавиту, без учёта регистра";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "числовой";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "по алфавиту";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "создать список из текста";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "создать текст из списка";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "Соединяет список текстов в один текст, разделяя его разделителем.";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Разделяет текст на список текстов по разделителям.";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "с разделителем";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "ложь";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "Возвращает либо истину, либо ложь.";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "истина";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://ru.wikipedia.org/wiki/Неравенство";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "Возвращает true, если оба значения равны.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "Возвращает true, если первое значение больше второго.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "Возвращает true, если первое значение больше или равно второму.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "Возвращает true, если первое значение меньше второго.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "Возвращает true, если первое значение меньше или равно второму.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Возвращает true, если оба значения не равны.";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "не %1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "Возвращает true, если входное значение ложно, и false, если оно истинно.";
Blockly.Msg["LOGIC_NULL"] = "ничего";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "Возвращает null.";
Blockly.Msg["LOGIC_OPERATION_AND"] = "и";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";
Blockly.Msg["LOGIC_OPERATION_OR"] = "или";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "Возвращает true, если оба входных значения истинны.";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "Возвращает true, если хотя бы одно входное значение истинно.";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "проверка";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "если ложь";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "если истина";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "Проверяет условие. Если оно истинно, возвращает значение «если истина», иначе — значение «если ложь».";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Возвращает сумму двух чисел.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Возвращает частное от деления двух чисел.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Возвращает разность двух чисел.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Возвращает произведение двух чисел.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Возводит первое число в степень второго.";
Blockly.Msg["MATH_ATAN2_HELPURL"] = "https://en.wikipedia.org/wiki/Atan2";
Blockly.Msg["MATH_ATAN2_TITLE"] = "atan2 от X:%1 Y:%2";
Blockly.Msg["MATH_ATAN2_TOOLTIP"] = "Возвращает  arctangent of point (X, Y) in degrees from -180 to 180.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg["MATH_CHANGE_TITLE"] = "change %1 by %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "Добавляет число к переменной «%1».";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "Возвращает one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "ограничить %1 снизу %2 сверху %3";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "Constrain a число to be between the specified limits (inclusive).";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "делится на";
Blockly.Msg["MATH_IS_EVEN"] = "чётное";
Blockly.Msg["MATH_IS_NEGATIVE"] = "отрицательное";
Blockly.Msg["MATH_IS_ODD"] = "нечётное";
Blockly.Msg["MATH_IS_POSITIVE"] = "положительное";
Blockly.Msg["MATH_IS_PRIME"] = "простое";
Blockly.Msg["MATH_IS_TOOLTIP"] = "Проверяет, является ли число чётным, нечётным, простым, целым, положительным, отрицательным или делится ли оно на заданное число. Возвращает true или false.";
Blockly.Msg["MATH_IS_WHOLE"] = "целое";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg["MATH_MODULO_TITLE"] = "остаток от %1 ÷ %2";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "Возвращает остаток от деления двух чисел.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "Число.";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "среднее списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "максимум списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "медиана списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "минимум списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "моды списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "случайный элемент списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "стандартное отклонение списка";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "сумма списка";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Возвращает среднее арифметическое числовых значений списка.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "Возвращает наибольшее число в списке.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Возвращает медиану списка.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "Возвращает  smallest число in the список.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "Возвращает список наиболее часто встречающихся элементов.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "Возвращает случайный элемент списка.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Возвращает стандартное отклонение списка.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "Возвращает сумму всех чисел в списке.";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "случайная дробь";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "Возвращает случайную дробь от 0.0 (включительно) до 1.0 (не включая 1.0).";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "случайное целое число от %1 до %2";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "Возвращает случайное целое число между указанными пределами, включая границы.";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "округлить";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "округлить вниз";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "округлить вверх";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "Округляет число вверх или вниз.";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://ru.wikipedia.org/wiki/Квадратный_корень";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "модуль";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "квадратный корень";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "Возвращает модуль числа.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "Возвращает e в степени числа.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "Возвращает натуральный логарифм числа.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "Возвращает десятичный логарифм числа.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "Возвращает противоположное число.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "Возвращает 10 в степени числа.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "Возвращает квадратный корень числа.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";
Blockly.Msg["MATH_TRIG_COS"] = "cos";
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";
Blockly.Msg["MATH_TRIG_TAN"] = "tan";
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "Возвращает  arccosine of a число.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "Возвращает  arcsine of a число.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "Возвращает  arctangent of a число.";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "Возвращает  cosine of a degree (not radian).";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "Возвращает  sine of a degree (not radian).";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "Возвращает  tangent of a degree (not radian).";
Blockly.Msg["NEW_COLOUR_VARIABLE"] = "Создать переменную цвета…";
Blockly.Msg["NEW_NUMBER_VARIABLE"] = "Создать числовую переменную…";
Blockly.Msg["NEW_STRING_VARIABLE"] = "Создать строковую переменную…";
Blockly.Msg["NEW_VARIABLE"] = "Создать переменную…";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "Имя новой переменной:";
Blockly.Msg["NEW_VARIABLE_TYPE_TITLE"] = "Новый тип переменной:";
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "";
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "разрешить операторы";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "с:";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Выполнить пользовательскую функцию «%1».";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "Выполнить пользовательскую функцию «%1» и использовать её результат.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "с:";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "Создать «%1»";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "Опишите эту функцию…";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "выполнить что-то";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "чтобы";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Создаёт функцию без возвращаемого значения.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "вернуть";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "Создаёт функцию с возвращаемым значением.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Предупреждение: эта функция содержит повторяющиеся параметры.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "Выделить определение функции";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "If a value is true, then return a second value.";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "Предупреждение: этот блок можно использовать только внутри определения функции.";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "имя входного параметра:";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "Добавить входной параметр в функцию.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "параметры";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Добавить, удалить или изменить порядок входных параметров этой функции.";
Blockly.Msg["REDO"] = "Повторить";
Blockly.Msg["REMOVE_COMMENT"] = "Удалить комментарий";
Blockly.Msg["RENAME_VARIABLE"] = "Переименовать переменную…";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "Переименовать все переменные «%1» в:";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg["TEXT_APPEND_TITLE"] = "к %1 добавить текст %2";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "Добавить текст к переменной «%1».";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "в нижний регистр";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "с заглавной буквы";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "в верхний регистр";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "Возвращает копию текста в другом регистре.";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "получить первую букву";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "получить букву № с конца";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "получить букву №";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";
Blockly.Msg["TEXT_CHARAT_LAST"] = "получить последнюю букву";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "получить случайную букву";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "";
Blockly.Msg["TEXT_CHARAT_TITLE"] = "в тексте %1 %2";
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "Возвращает букву в указанной позиции.";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "подсчитать количество %1 в %2";
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "Подсчитать, сколько раз один текст встречается внутри другого.";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Добавить элемент в текст.";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "объединить";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "Добавить, удалить или изменить порядок частей этого текстового блока.";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "до буквы № с конца";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "до буквы №";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "до последней буквы";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "в тексте";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "получить подстроку с первой буквы";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "получить подстроку с буквы № с конца";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "получить подстроку с буквы №";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "Возвращает указанную часть текста.";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "найти первое вхождение текста";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "найти последнее вхождение текста";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "в тексте %1 %2 %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "Возвращает позицию первого или последнего вхождения одного текста в другой. Возвращает %1, если текст не найден.";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1 пуст";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "Возвращает true, если указанный текст пуст.";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "создать текст из";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "Создаёт фрагмент текста, объединяя любое количество элементов.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg["TEXT_LENGTH_TITLE"] = "длина %1";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "Возвращает число символов в тексте, включая пробелы.";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";
Blockly.Msg["TEXT_PRINT_TITLE"] = "вывести %1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "Печатает указанный текст, число или другое значение.";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Запросить у пользователя число.";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "Запросить у пользователя текст.";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "запросить число с сообщением";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "запросить текст с сообщением";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "заменить %1 на %2 в %3";
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "Заменить все вхождения одного текста в другом.";
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "изменить порядок %1 на обратный";
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "Изменяет порядок символов в тексте на обратный.";
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "A letter, word, or line of текст.";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "удалить пробелы с обеих сторон";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "удалить пробелы слева";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "удалить пробелы справа";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "Возвращает копию текста без пробелов с одного или обоих концов.";
Blockly.Msg["TODAY"] = "Сегодня";
Blockly.Msg["UNDO"] = "Отменить";
Blockly.Msg["UNNAMED_KEY"] = "без названия";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "элемент";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "Создать «присвоить %1»";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "Возвращает значение этой переменной.";
Blockly.Msg["VARIABLES_SET"] = "присвоить %1 значение %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "Создать «получить %1»";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "Присваивает переменной значение входного параметра.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "A переменную named '%1' already exists.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "A переменную named '%1' already exists for another type: '%2'.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_A_PARAMETER"] = "A переменную named '%1' already exists as a parameter in the procedure '%2'.";
Blockly.Msg["WORKSPACE_ARIA_LABEL"] = "Рабочая область Blockly";
Blockly.Msg["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Напишите что-нибудь…";
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_APPEND_VARIABLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];

Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";
Blockly.Msg["PROCEDURES_HUE"] = "290";


// Drone Commands
Blockly.Msg["BKY_DRONE_TAKEOFF"] = "взлететь";
Blockly.Msg["BKY_DRONE_TAKEOFF_TOOLTIP"] = "Выполнить взлёт дрона";

Blockly.Msg["BKY_DRONE_LAND"] = "приземлиться";
Blockly.Msg["BKY_DRONE_LAND_TOOLTIP"] = "Выполнить посадку дрона";
Blockly.Msg["BKY_DRONE_TAKE_PHOTO"] = "сделать фото";
Blockly.Msg["BKY_DRONE_TAKE_PHOTO_TOOLTIP"] = "Скачать изображение PNG с камеры дрона";
Blockly.Msg["BKY_DRONE_START_RECORDING"] = "начать запись";
Blockly.Msg["BKY_DRONE_START_RECORDING_TOOLTIP"] = "Начать запись видео с камеры дрона";
Blockly.Msg["BKY_DRONE_SAVE_RECORDING"] = "сохранить запись";
Blockly.Msg["BKY_DRONE_SAVE_RECORDING_TOOLTIP"] = "Остановить запись и скачать видео с камеры дрона";

Blockly.Msg["BKY_DRONE_SET_ALTITUDE"] = "задать высоту %1";
Blockly.Msg["BKY_DRONE_SET_ALTITUDE_TOOLTIP"] = "Задать высоту дрона";

Blockly.Msg["BKY_DRONE_CHANGE_ALTITUDE"] = "изменить высоту на %1";
Blockly.Msg["BKY_DRONE_CHANGE_ALTITUDE_TOOLTIP"] = "Изменить высоту дрона";

Blockly.Msg["BKY_DRONE_SET_ANGLE"] = "задать угол %1";
Blockly.Msg["BKY_DRONE_SET_ANGLE_TOOLTIP"] = "Задать угол дрона";

Blockly.Msg["BKY_DRONE_CHANGE_ANGLE"] = "изменить угол на %1";
Blockly.Msg["BKY_DRONE_CHANGE_ANGLE_TOOLTIP"] = "Изменить угол дрона";

Blockly.Msg["BKY_DRONE_SLIDE"] = "сместиться на %1";
Blockly.Msg["BKY_DRONE_SLIDE_TOOLTIP"] = "Сместить дрон в сторону";

Blockly.Msg["BKY_DRONE_WALK"] = "двигаться на %1";
Blockly.Msg["BKY_DRONE_WALK_TOOLTIP"] = "Переместить дрон вперёд";

Blockly.Msg["BKY_DRONE_WALK_CLIMBING"] = "двигаться вперёд на %1 с подъёмом на %2";
Blockly.Msg["BKY_DRONE_WALK_CLIMBING_TOOLTIP"] = "Переместить дрон вперёд с набором высоты";

Blockly.Msg["BKY_DRONE_GO_TO"] = "перейти в x %1 y %2 z %3";
Blockly.Msg["BKY_DRONE_GO_TO_TOOLTIP"] = "Переместить дрон в абсолютную позицию с текущей скоростью";

Blockly.Msg["BKY_DRONE_MOVE_BY"] = "сместиться на x %1 y %2 z %3";
Blockly.Msg["BKY_DRONE_MOVE_BY_TOOLTIP"] = "Переместиться относительно текущего направления: X вправо/влево, Y вперёд/назад, Z вверх/вниз";

Blockly.Msg["BKY_DRONE_CURVE_ABS"] = "пролететь по кривой abs x %1 y %2 z %3 xd %4 yd %5 zd %6";
Blockly.Msg["BKY_DRONE_CURVE_ABS_TOOLTIP"] = "Пролететь по кривой через текущую позицию, абсолютную промежуточную точку и абсолютную конечную точку";

Blockly.Msg["BKY_DRONE_CURVE"] = "пролететь по кривой x %1 y %2 z %3 xd %4 yd %5 zd %6";
Blockly.Msg["BKY_DRONE_CURVE_TOOLTIP"] = "Пролететь по кривой с относительными точками: X вправо/влево, Y вперёд/назад, Z вверх/вниз";

Blockly.Msg["BKY_DRONE_RETURN_TO_BASE"] = "вернуться на базу";
Blockly.Msg["BKY_DRONE_RETURN_TO_BASE_TOOLTIP"] = "Вернуть дрон на базу с текущей скоростью";

Blockly.Msg["BKY_DRONE_WAIT"] = "ждать %1";
Blockly.Msg["BKY_DRONE_WAIT_TOOLTIP"] = "Приостановить дрон";

Blockly.Msg["BKY_DRONE_SMOKE"] = "дым %1";
Blockly.Msg["BKY_DRONE_SMOKE_TOOLTIP"] = "Выпустить дым из дрона";

Blockly.Msg["BKY_DRONE_SPEED"] = "скорость %1";
Blockly.Msg["BKY_DRONE_SPEED_TOOLTIP"] = "Задать скорость дрона (от 0 до 10)";


// Sensor Blocks
Blockly.Msg["BKY_SENSOR_KEYPRESSED"] = "нажата клавиша %1";
Blockly.Msg["BKY_SENSOR_KEYPRESSED_TOOLTIP"] = "Возвращает true, если клавиша была нажата";

Blockly.Msg["ARROW_UP"]="Arrow Up"; 
Blockly.Msg["ARROW_DOWN"]="Arrow Down";
Blockly.Msg["ARROW_LEFT"]="Arrow Left"; 
Blockly.Msg["ARROW_RIGHT"]="Arrow Right";
Blockly.Msg["SPACE"]="Space"; 
Blockly.Msg["RETURN"]="Return";

Blockly.Msg["BKY_SENSOR_X"] = "X";
Blockly.Msg["BKY_SENSOR_X_TOOLTIP"] = "Возвращает координату X дрона";

Blockly.Msg["BKY_SENSOR_Y"] = "Y";
Blockly.Msg["BKY_SENSOR_Y_TOOLTIP"] = "Возвращает координату Y дрона";

Blockly.Msg["BKY_SENSOR_Z"] = "Z";
Blockly.Msg["BKY_SENSOR_Z_TOOLTIP"] = "Возвращает высоту дрона как координату Z";

Blockly.Msg["BKY_SENSOR_ALTITUDE"] = "Высота";
Blockly.Msg["BKY_SENSOR_ALTITUDE_TOOLTIP"] = "Возвращает высоту дрона";

Blockly.Msg["BKY_SENSOR_DIRECTION"] = "Направление";
Blockly.Msg["BKY_SENSOR_DIRECTION_TOOLTIP"] = "Возвращает направление дрона";

Blockly.Msg["BKY_SENSOR_SPEED"] = "скорость";
Blockly.Msg["BKY_SENSOR_SPEED_TOOLTIP"] = "Возвращает скорость дрона";


// Flow
Blockly.Msg["BKY_FLOW_START_TOOLTIP"] = "начало программы";
Blockly.Msg["BKY_FLOW_END_TOOLTIP"] = "остановка программы";

Blockly.Msg["BKY_FLOW_START"] = "Начало";
Blockly.Msg["BKY_FLOW_END"] = "Конец";


// menu
Blockly.Msg.BKY_NEW = "Создать";
Blockly.Msg.BKY_LOAD = "Загрузить";
Blockly.Msg.BKY_SAVE = "Сохранить";

Blockly.Msg.BKY_HELP = "Помощь";
Blockly.Msg.BKY_SCENARIO = "Сценарий";
Blockly.Msg.BKY_SCENARIO_ADD = "Создать сценарий";
Blockly.Msg.BKY_SCENARIO_DEFAULT = "Новый сценарий";
Blockly.Msg.BKY_NEW_PROGRAM = "Новая программа";
Blockly.Msg.BKY_SCENARIO_EDIT = "Редактировать сценарий";
Blockly.Msg.BKY_SCENARIO_NAME = "Название";
Blockly.Msg.BKY_SCENARIO_DATA = "Данные сценария (JSON)";
Blockly.Msg.BKY_SCENARIO_EDITOR = "Редактор сценариев";
Blockly.Msg.BKY_SCENARIO_VISUAL_EDIT = "Открыть графический редактор карты";
Blockly.Msg.BKY_SCENARIO_VISUAL_RETURNED = "Данные карты получены. Сохраните сценарий в этой вкладке.";
Blockly.Msg.BKY_SCENARIO_POPUP_BLOCKED = "Разрешите всплывающие окна, чтобы открыть редактор в новой вкладке.";
Blockly.Msg.BKY_SCENARIO_CANCEL = "Отмена";
Blockly.Msg.BKY_SCENARIO_INVALID = "Введите корректный JSON сценария с массивом объектов.";
Blockly.Msg.BKY_SCENARIO_STORAGE_ERROR = "Не удалось сохранить сценарий в браузере.";
Blockly.Msg.BKY_FILE_NAME = "безымянный";
Blockly.Msg.BKY_SAVE_PROMPT = "Имя файла:";
Blockly.Msg.BKY_GRAPHICS = "Графика";
Blockly.Msg.BKY_GRAPHICS_PERFORMANCE = "Производительность";
Blockly.Msg.BKY_GRAPHICS_BALANCED = "Сбалансированно";
Blockly.Msg.BKY_GRAPHICS_QUALITY = "Качество";
Blockly.Msg.BKY_STATUS_X = "X:";
Blockly.Msg.BKY_STATUS_Y = "Y:";
Blockly.Msg.BKY_STATUS_Z = "Z:";
Blockly.Msg.BKY_STATUS_ALTITUDE = "Высота:";
Blockly.Msg.BKY_STATUS_DIRECTION = "Направление:";
Blockly.Msg.BKY_STATUS_FLIGHT = "Статус:";
Blockly.Msg.BKY_FLIGHT_IN_FLIGHT = "В полёте";
Blockly.Msg.BKY_FLIGHT_ON_GROUND = "На земле";
Blockly.Msg.BKY_CAMERA_PREVIEW = "Предпросмотр камеры";
Blockly.Msg.BKY_DARK_THEME = "Тёмная тема";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY = "Папка фото/видео:";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY_SELECT = "Выбрать...";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY_RESET = "Сброс";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY_DEFAULT = "Папка загрузок браузера";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY_UNSUPPORTED = "Папка загрузок браузера (выбор папки не поддерживается)";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY_PERMISSION_NEEDED = "нужно разрешение";
Blockly.Msg.BKY_MEDIA_SAVE_DIRECTORY_PRIVACY = "Для конфиденциальности браузер показывает только выбранное имя папки.";


// Category
Blockly.Msg["BKY_CATEGORY_LOGIC"]="Логика";
Blockly.Msg["BKY_CATEGORY_LOOPS"]="Циклы";
Blockly.Msg["BKY_CATEGORY_MATH"]="Математика";
Blockly.Msg["BKY_CATEGORY_TEXT"]="Текст";
Blockly.Msg["BKY_CATEGORY_LISTS"]="Списки";
Blockly.Msg["BKY_CATEGORY_VARIABLES"]="Переменные";
Blockly.Msg["BKY_CATEGORY_FUNCTIONS"]="Функции";
Blockly.Msg["BKY_CATEGORY_SENSORS"]="Датчики";
Blockly.Msg["BKY_CATEGORY_DRONE"]="Дрон";
Blockly.Msg["BKY_CATEGORY_FLOW"]="Поток";



return Blockly.Msg;
}));
